pipeline:
  build:
    image: python:${PYTHON_VERSION}-stretch
    commands:
      - python -m venv .venv
      - . .venv/bin/activate
      - pip install -r requirements.txt
      - pip install -r flake8-requirements.txt
      - pip install -e .

  full-tests:
    image: python:${PYTHON_VERSION}-stretch
    commands:
      - apt-get update
      - apt-get install -yq --no-install-recommends openjdk-8-jre
      - . .venv/bin/activate
      - pytest --run-e2e --doctest-modules
      - flake8

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    webhook: ${SLACK_WEBHOOK}
    channel: shop-data-eng-ci
    username: ${CI_REPO_NAME}
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        :tada: {{build.link}} ({{build.branch}}) - (Python ${PYTHON_VERSION})
      {{else}}
        :facepalm: {{build.link}} ({{build.branch}}) - (Python ${PYTHON_VERSION})
      {{/success}}
      

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  broker:
    image: confluentinc/cp-kafka:5.0.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0

  schema-registry:
    image: confluentinc/cp-schema-registry:5.0.0-beta30
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - 8081:8081
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181

  rest-proxy:
    image: confluentinc/cp-kafka-rest:latest
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    ports:
      - 8082:8082
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      - KAFKA_REST_HOST_NAME=rest-proxy
      - KAFKA_REST_BOOTSTRAP_SERVERS=broker:9092
      - KAFKA_REST_LISTENERS=http://0.0.0.0:8082
      - KAFKA_REST_SCHEMA_REGISTRY_URL=http://schema-registry:8081

matrix:
  PYTHON_VERSION:
    - 3.6
    - 3.7
